# Generated by Django 3.0.7 on 2020-06-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username_en_us',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username_es',
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender_en_us',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender_es',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True, verbose_name='Gender'),
        ),
    ]
